using System;

namespace Electrolyte {
	public partial class Script {
		public enum Op : byte {
			False               = 0x00,
			PushData            = 0x4B,
			PushData1           = 0x4C,
			PushData2           = 0x4D,
			PushData4           = 0x4E,
			Negate1             = 0x4F,
			True                = 0x51,
			Num2                = 0x52,
			Num3                = 0x53,
			Num4                = 0x54,
			Num5                = 0x55,
			Num6                = 0x56,
			Num7                = 0x57,
			Num8                = 0x58,
			Num9                = 0x59,
			Num10               = 0x5A,
			Num11               = 0x5B,
			Num12               = 0x5C,
			Num13               = 0x5D,
			Num14               = 0x5E,
			Num15               = 0x5F,
			Num16               = 0x60,

			Nop                 = 0x61,
			If                  = 0x63,
			NotIf               = 0x64,
			Else                = 0x67,
			EndIf               = 0x68,
			Verify              = 0x69,
			Return              = 0x6A,

			ToAltStack          = 0x6B,
			FromAltStack        = 0x6C,
			Drop2               = 0x6D,
			Dup2                = 0x6E,
			Dup3                = 0x6F,
			Over2               = 0x70,
			Rot2                = 0x71,
			Swap2               = 0x72,
			IfDup               = 0x73,
			Depth               = 0x74,
			Drop                = 0x75,
			Dup                 = 0x76,
			Nip                 = 0x77,
			Over                = 0x78,
			Pick                = 0x79,
			Roll                = 0x7A,
			Rot                 = 0x7B,
			Swap                = 0x7C,
			Tuck                = 0x7D,

			Cat                 = 0x7E,
			SubStr              = 0x7F,
			Left                = 0x80,
			Right               = 0x81,
			Size                = 0x82,

			Invert              = 0x83,
			And                 = 0x84,
			Or                  = 0x85,
			Xor                 = 0x86,
			Equal               = 0x87,
			EqualVerify         = 0x88,

			Add1                = 0x8B,
			Sub1                = 0x8C,
			Mul2                = 0x8D,
			Div2                = 0x8E,
			Negate              = 0x8F,
			Abs                 = 0x90,
			Not                 = 0x91,
			NotEqual0           = 0x92,
			Add                 = 0x93,
			Sub                 = 0x94,
			Mul                 = 0x95,
			Div                 = 0x96,
			Mod                 = 0x97,
			LShift              = 0x98,
			RShift              = 0x99,
			BoolAnd             = 0x9A,
			BoolOr              = 0x9B,
			NumEqual            = 0x9C,
			NumEqualVerify      = 0x9D,
			NumNotEqual         = 0x9E,
			LessThan            = 0x9F,
			GreaterThan         = 0xA0,
			LessThanOrEqual     = 0xA1,
			GreaterThanOrEqual  = 0xA2,
			Min                 = 0xA3,
			Max                 = 0xA4,
			Within              = 0xA5,

			RIPEMD160           = 0xA6,
			SHA1                = 0xA7,
			SHA256              = 0xA8,
			Hash160             = 0xA9,
			Hash256             = 0xAA,
			CodeSeparator       = 0xAB,
			CheckSig            = 0xAC,
			CheckSigVerify      = 0xAD,
			CheckMultiSig       = 0xAE,
			CheckMultiSigVerify = 0xAF,

			PubKeyHash          = 0xFD,
			PubKey              = 0xFE,
			InvalidOpCode       = 0xFF,

			Reserved            = 0x50,
			Ver                 = 0x62,
			VerIf               = 0x65,
			VerNotIf            = 0x66,
			Reserved1           = 0x89,
			Reserved2           = 0x8A,
			Nop1                = 0xB0,
			Nop2                = 0xB1,
			Nop3                = 0xB2,
			Nop4                = 0xB3,
			Nop5                = 0xB4,
			Nop6                = 0xB5,
			Nop7                = 0xB6,
			Nop8                = 0xB7,
			Nop9                = 0xB8,
			Nop10               = 0xB9
		}
	}
}

